### ISSUE TITLE
Typo in example results

### ISSUE THREAD

**Issue by ssslakter** [AnswerDotAI/fastdata#2]
Hi! The experiments are very interesting! 
I think there may be a typo in the results table (or correct me if I'm wrong). The Stack shows 11.0% pass@1, and TinyPrograms has 09.1%, which seems contrary to the statement:

> Training on synthetic data is better than training on random GitHub programs, even with quality filtering (TinyPrograms vs The Stack, and TinyPrograms Filtered vs The Stack Filtered).

**Comment by ncoop57** [comment]
Ah thank you for the good catch! I've fixed the typo!!
